---
mas_email: ""
mas_password: ""
mas_installed_apps:
    # - { id: 497799835, name: "Xcode (8.3.3)" }
    - { id: 715768417, name: "Microsoft Remote Desktop" }
    - { id: 1176895641, name: "Spark - Love your email again" }
    - { id: 784801555, name: "Microsoft OneNote" }
    - { id: 491854842, name: "Youdao Dictionary" }
mas_upgrade_all_apps: yes
mas_signin_dialog: yes
